default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: govuk_preview_app_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: govuk_preview_app_test
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
  database: govuk_preview_app_production
  url: <%= ENV["DATABASE_URL"] %>
